services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-mock-backend
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    volumes:
      - ./backend/api_mocks.db:/app/api_mocks.db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args: 
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      dockerfile: Dockerfile
    container_name: api-mock-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend
    restart: unless-stopped
